# Generated by Django 3.1 on 2020-08-31 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField(default=2000)),
                ('banner', models.URLField(blank=True, default='', null=True)),
                ('type', models.CharField(choices=[('film', 'FILM'), ('series', 'SERIES')], max_length=6)),
                ('age', models.PositiveIntegerField(default=3)),
                ('movie_trailer', models.URLField(blank=True, null=True)),
                ('runing_time', models.PositiveIntegerField(default=120)),
                ('country', models.CharField(default='USA', max_length=200)),
                ('category', models.CharField(choices=[('action', 'ACTION'), ('drama', 'Drama'), ('', '')], default='', max_length=10)),
                ('views_count', models.IntegerField(default=0)),
                ('quality', models.CharField(default='HD', max_length=15)),
                ('link_hd', models.URLField(blank=True, null=True)),
                ('link_720', models.URLField(blank=True, null=True)),
                ('link_480', models.URLField(blank=True, null=True)),
                ('link_240', models.URLField(blank=True, null=True)),
                ('link_144', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('banner', models.URLField(blank=True, null=True)),
                ('trailer', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250)),
                ('season_num', models.IntegerField(default=1)),
                ('banner', models.URLField(blank=True, null=True)),
                ('trailer', models.URLField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_season', to='movie.series')),
            ],
        ),
        migrations.CreateModel(
            name='MovieImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_photo', to='movie.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='movie.season'),
        ),
    ]
