# Generated by Django 3.1 on 2020-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'Drama')], default='action', max_length=10),
        ),
        migrations.AddField(
            model_name='series',
            name='year',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'Drama')], max_length=10),
        ),
    ]
