# Generated by Django 3.1 on 2020-08-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200831_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
