# Generated by Django 3.1 on 2020-08-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='series',
        ),
    ]
