# Generated by Django 3.1 on 2020-08-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_movie_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_movie', to='movie.series'),
        ),
    ]
