# Generated by Django 3.1 on 2020-08-31 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='season',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='series',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_num', models.IntegerField(default=1)),
                ('banner', models.URLField(blank=True, default='', null=True)),
                ('episode_trailer', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('age', models.PositiveIntegerField(default=3)),
                ('views_count', models.IntegerField(default=0)),
                ('quality', models.CharField(default='HD', max_length=15)),
                ('link_hd', models.URLField(blank=True, null=True)),
                ('link_720', models.URLField(blank=True, null=True)),
                ('link_480', models.URLField(blank=True, null=True)),
                ('link_240', models.URLField(blank=True, null=True)),
                ('link_144', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='movie.season')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_movie', to='movie.series')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
