# Generated by Django 3.1 on 2020-09-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20200901_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
