# Generated by Django 3.1 on 2020-09-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
