# Generated by Django 3.1 on 2020-09-01 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(default='Action', on_delete=django.db.models.deletion.CASCADE, to='movie.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.ForeignKey(default='Action', on_delete=django.db.models.deletion.CASCADE, to='movie.category'),
            preserve_default=False,
        ),
    ]
