# Generated by Django 3.1 on 2020-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_auto_20200901_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug_movie',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_series',
            field=models.SlugField(max_length=250),
        ),
    ]
