# Generated by Django 3.1 on 2020-09-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_auto_20200901_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('created',)},
        ),
    ]
