# Generated by Django 3.1 on 2020-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0028_episode_runing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='country',
            field=models.CharField(default='USA', max_length=200),
        ),
    ]
