# Generated by Django 3.1 on 2020-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0030_remove_season_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='country',
            field=models.CharField(default='USA', max_length=200),
        ),
    ]
