# Generated by Django 3.1 on 2020-09-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0031_series_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='air_date',
            field=models.DateField(default='7-8-2020'),
        ),
    ]
