# Generated by Django 3.1 on 2020-09-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0033_auto_20200901_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='air_date',
        ),
    ]
