# Generated by Django 3.1 on 2020-09-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0035_episode_air_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_photo', to='movie.series')),
            ],
        ),
    ]
