# Generated by Django 3.1 on 2020-09-01 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0036_seriesimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesimages',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='series_photo', to='movie.series'),
        ),
    ]
