# Generated by Django 3.1 on 2020-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0038_auto_20200901_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='link_360',
            field=models.URLField(blank=True, null=True),
        ),
    ]
