# Generated by Django 3.1 on 2020-09-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0040_auto_20200902_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='views_count',
        ),
    ]
