# Generated by Django 3.1 on 2020-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0042_auto_20200903_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='trailer',
        ),
        migrations.AddField(
            model_name='episode',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=7.4, max_digits=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=7.4, max_digits=3),
        ),
        migrations.AddField(
            model_name='series',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=7.4, max_digits=3),
        ),
    ]
